openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: List users
      responses:
        '200': {description: OK}
    post:
      summary: Create user
      responses:
        '201': {description: Created}
